### ISSUE TITLE
more functions

### ISSUE THREAD

**Issue by jtravs** [JuliaMath/openspecfun#10]
Is it possible to add more special functions here, for eventual use in Julia. (I'm willing to do the work). In particular I am currently interested in zeros of the bessel functions, and the hypergeometric functions. There are implementations on netlib (i.e. in cephes or specfun.f) which should have a compatible license as they are used in scipy. If this is OK, I will start to work on a trial pull request.

**Comment by ViralBShah** [comment]
We now have a much better binary building infrastructure, and thus should not need to add more stuff in here.
