### ISSUE TITLE
USE_SYSTEM_OPENLIBM

### ISSUE THREAD

**Issue by staticfloat** [JuliaMath/openspecfun#11]
@nalimilan I'm assuming we will need to have some kind of `USE_SYSTEM_OPENLIBM` here, right?  Looking at `Make.inc`, it looks like the `USE_OPENLIBM` macro is specifically expecting to be sitting in the Julia source tree, with `openlibm` sitting next to it.

**Comment by ViralBShah** [comment]
I think we no longer have this assumption.
