### ISSUE TITLE
d1mach.f warning

### ISSUE THREAD

**Issue by starrynight** [JuliaMath/openspecfun#29]
When I compile the latest master branch on Ubuntu 14.04 with intel icc， I receive the following warining:

amos/d1mach.f(80): remark #7922: The value was too small when converting to REAL(KIND=8); the result  is in the denormalized range.   [1.79D-308]
      DATA DMACH(2) / 1.79D-308 /

The build can still pass through but I'm not certain of it's impact.

**Comment by ViralBShah** [comment]
We are no longer supporting `icc` for julia.
