### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by Keno** [JuliaMath/openspecfun#44]
It would be good to enable CI for both the openlibm and non-openlibm build (ideally both glibc and musl). cc @tkelman

**Comment by albap** [comment]
+1

**Comment by tkelman** [comment]
Testing musl on travis would not be straightforward. On an alternative service to travis that lets you more easily run all tests in a docker container of your choosing, maybe. Someone needs to writr tests and put the build steps in a yml file. That effort may be better spent porting this code to Julia though, finishing up https://github.com/nolta/SpecialFunctions.jl

**Comment by Keno** [comment]
Ok, at least the glibc build then.

**Comment by tkelman** [comment]
There's a chance I may have already enabled it but with "only build branches with .travis.yml" set.
