### ISSUE TITLE
Possible hankelh1 bug

### ISSUE THREAD

**Issue by ihnorton** [JuliaMath/openspecfun#45]
From: https://groups.google.com/d/msg/julia-users/d7WwRqZtUGw/wwixIGiRBAAJ

This appears to be an AMOS issue, as SciPy and SciLab give the same answer (and both use AMOS from what I gather). Wolfram Alpha and mpmath give the correct answer.

```
> hankelh1(1,2e-32)
1.9490859162596872e15 - 3.1830988618379058e31im
```

whereas:

```
> besselj(1,2e-32) + im*bessely(1,2e-32)
1.0e-32 - 3.1830988618379067e31im
```

possibly related: https://github.com/scipy/scipy/issues/4517

**Comment by ViralBShah** [comment]
Should we also file this in SpecialFunctions.jl?

**Comment by ViralBShah** [comment]
Now, both give the same results in Julia and matches with [Wolfram Alpha](https://www.wolframalpha.com/input/?i=HankelH1%5B1%2C2e-32%5D).

```
julia> hankelh1(1,2e-32)
1.0e-32 - 3.1830988618379067e31im

julia> besselj(1,2e-32) + im*bessely(1,2e-32)
1.0e-32 - 3.1830988618379067e31im
```

I think this can be marked as fixed.
