### ISSUE TITLE
Tag 0.5.4?

### ISSUE THREAD

**Issue by mcabbott** [JuliaMath/openspecfun#54]
There are a few commits since 0.5.3: https://github.com/JuliaMath/openspecfun/releases/tag/v0.5.3

Having a patch release would allow a new `OpenSpecFun_jll` with matching version number, for  https://github.com/JuliaPackaging/Yggdrasil/issues/2763

**Comment by giordano** [comment]
Bump.  This would be useful to build openspecfun for aarch64-apple-darwin.  CC @ViralBShah

**Comment by ViralBShah** [comment]
Let's do it.

**Comment by ViralBShah** [comment]
Tagged 0.5.4.

**Comment by ViralBShah** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/2892
