### ISSUE TITLE
Can we remove rem_pio2 from openspecfun?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/openspecfun#56]
I believe we no longer use `rem_pio2` from this package in SpecialFunctions.jl or anywhere else. Would it be ok to remove it altogether, especially since we have a native implementation in base?

https://github.com/JuliaLang/julia/blob/master/base/special/rem_pio2.jl 

cc @stevengj @KristofferC

**Comment by KristofferC** [comment]
Seems reasonable to me but I don't know if this project is used outside of Julia.

**Comment by ViralBShah** [comment]
Pretty sure nobody uses it outside of Julia. I suppose they can use the older releases, as it is just a collection of amos, Fadeeva and rem_pio2.
