### ISSUE TITLE
Clarify licensing as MIT

### ISSUE THREAD

**Issue by mkitti** [JuliaMath/openspecfun#58]
The LICENSE.md currently specifies the license of components of this library. It does fully clarify what the overall license of the combined work.

**Comment by ViralBShah** [comment]
Since it brings together different parts, the combined license is the collection of the individual pieces. Not sure we can redistribute under a different license.

**Comment by mkitti** [comment]
Right, but there is content in this repository that is part of neither library, such as the CMakeLists.txt. What is that licensed under?

**Comment by ViralBShah** [comment]
Ah I see - those should go as MIT. Updated in e98d4f427a20af69cb6f592ff65634f00e97b638
