### ISSUE TITLE
Would it be possible to add an option to use `cmake` as the configuration tool?

### ISSUE THREAD

**Issue by Ionizing** [JuliaMath/openspecfun#60]
Hi, I've been using Julia for several years, and find SpecialFunctions.jl runs pretty fast. It beats both [scipy.special](https://docs.scipy.org/doc/scipy/reference/special.html) and GNU-GSL. Thus I want to port it to Rust using [build.rs](https://doc.rust-lang.org/cargo/reference/build-scripts.html), which would depends on `cmake`. I tried to write a `CMakeLists.txt` and the build results are same with original `makefile`'s. So would it be possible that I make a PR to add the `CMakeLists.txt` to this repo?

You can read the `CMakeLists.txt` at [here](https://github.com/Ionizing/openspecfun/blob/00b74b8e8dd11a07ce84fe99ca588a79d088c859/CMakeLists.txt) if you have interest.

**Comment by ViralBShah** [comment]
Yes, that would be fine. We can also then update the build system here as well.
